
name: vehicle_tracker
description: A vehicle location tracking application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase packages
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_database: ^11.2.0

  # Location tracking
  geolocator: 13.0.1

  mobile_scanner: ^6.0.7
  permission_handler: ^10.2.0

  # Other utilities
  intl: ^0.19.0
  http: ^1.2.1

  flutter_background_service: ^5.0.0
  flutter_background_service_android: ^6.0.0
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon1.png"
  adaptive_icon_foreground: "assets/icon/icon1.png"
  #  adaptive_icon_background: "#5F8F3C"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

  assets:
    - assets/icon/icon1.png


